version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/eclipse-temurin:21
    working_directory: ~/repo

jobs:
  build:
    executor: kotlin-maven-executor

    steps:
      - checkout
      - restore_cache:
            key: maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build and run tests
          command: mvn clean install -DskipTests=false
      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target
          destination: build-artifacts
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build